# Generated by Django 5.1.2 on 2024-11-29 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите ФИО врача', max_length=50)),
                ('education', models.TextField(help_text='Введите образование врача', max_length=1000)),
                ('experience', models.TextField(help_text='Введите опыт работы врача', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название услуги', max_length=100)),
                ('description', models.CharField(help_text='Введите описание услуги', max_length=200)),
                ('price', models.PositiveIntegerField(help_text='Введите стоимость услуги')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название специальности', max_length=30)),
                ('description', models.CharField(help_text='Введите описание специальности', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospWeb.doctor')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospWeb.speciality')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(help_text='Введите дату и время свободные для записи')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospWeb.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSpecialityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorSpeciality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospWeb.doctorspeciality')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospWeb.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospWeb.speciality'),
        ),
    ]
