# Generated by Django 5.1.2 on 2024-12-01 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospWeb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='dt',
            new_name='date',
        ),
        migrations.AddField(
            model_name='schedule',
            name='available',
            field=models.CharField(choices=[('a', 'Available'), ('u', 'Unavailable')], default='A', help_text='Доступна ли дата для записи', max_length=1),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('relevance', models.CharField(choices=[('a', 'Actual'), ('p', 'Past')], default='a', help_text='Актуальность записи', max_length=1)),
                ('date', models.OneToOneField(limit_choices_to={'schedule_available': 'a'}, on_delete=models.SET('deleted'), primary_key=True, serialize=False, to='hospWeb.schedule')),
                ('doc_spec_ser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospWeb.doctorspecialityservice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
