# Generated by Django 5.1.2 on 2024-12-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospWeb', '0002_rename_dt_schedule_date_schedule_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorspecialityservice',
            options={'permissions': (('some_permission', 'Some permission yeah'),)},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.OneToOneField(on_delete=models.SET('deleted'), primary_key=True, serialize=False, to='hospWeb.schedule'),
        ),
    ]
