# Generated by Django 5.1.2 on 2024-12-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospWeb', '0003_alter_doctorspecialityservice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='available',
            field=models.CharField(choices=[('a', 'Available'), ('u', 'Unavailable')], default='a', help_text='Доступна ли дата для записи', max_length=1),
        ),
    ]
