# Generated by Django 5.1.2 on 2024-12-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospWeb', '0004_alter_schedule_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doc_spec_ser',
            new_name='doc_spec_serv',
        ),
    ]
