# Generated by Django 5.1.2 on 2024-12-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospWeb', '0005_rename_doc_spec_ser_appointment_doc_spec_serv'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorspecialityservice',
            name='access',
            field=models.CharField(choices=[('u', 'User'), ('s', 'Staff')], default='u', help_text='Кто может создать запись', max_length=1),
        ),
    ]
