# Generated by Django 4.2.7 on 2024-12-04 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospWeb', '0006_doctorspecialityservice_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, default=3, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='hospWeb.schedule'),
        ),
    ]
