# Generated by Django 4.2.7 on 2024-12-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospWeb', '0007_appointment_id_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'permissions': (('change_appointment_staff', 'Staff can change all parameters of appointment'), ('create_appointment_user', 'Staff can change all parameters of appointment'))},
        ),
    ]
