# Generated by Django 4.2.7 on 2024-12-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospWeb', '0008_alter_appointment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default=1, help_text='Введите имя врача', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default=2, help_text='Введите фамилию врача', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='patronymic',
            field=models.CharField(default=3, help_text='Введите отчество врача', max_length=20),
            preserve_default=False,
        ),
    ]
