# Generated by Django 4.2.7 on 2024-12-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospWeb', '0009_remove_doctor_name_doctor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'permissions': (('create_appointment_user', 'User can create appointment'), ('change_appointment_user', 'User can change appointment'))},
        ),
        migrations.AlterModelOptions(
            name='doctorspecialityservice',
            options={},
        ),
    ]
