# Generated by Django 4.2.7 on 2024-12-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospWeb', '0010_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'permissions': (('create_appointment_visitor', 'Visitor can create appointment'), ('change_appointment_visitor', 'Visitor can change appointment'))},
        ),
    ]
