# Generated by Django 4.2.7 on 2024-12-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospWeb', '0011_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'permissions': (('create_appointment_visitor', 'Visitor can create appointment'), ('change_appointment_visitor', 'Visitor can change appointment'), ('view_appointments_visitor', 'Visitor can view appointments'), ('view_appointments', 'Staff can view appointments'))},
        ),
    ]
